#############
### build ###
#############

# base image
FROM node:10.19.0 as build

# install chrome for protractor tests
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
# RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@7.2.2

# add app
COPY . /app

# replace parameters value with the ones passed in docker build command param "--build-arg"
ARG backendURL
RUN perl -v
RUN perl -pi -e "s{apiPath:(.*)$}{apiPath: '$backendURL'}" src/environments/environment.prod.ts
RUN cat src/environments/environment.prod.ts

# run tests
# RUN ng test --watch=false
# RUN ng e2e --port 4202

# generate build
RUN ng build --prod="true"

RUN cat src/environments/environment.ts
