/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.2-SNAPSHOT - 282608d038dbfdf7754fa4e049f180f36e0f635a
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Criteria { 
    query?: string;
    fieldName?: string;
    operator?: string;
    position?: number;
    level?: number;
    filterQuery?: boolean;
    addonsFields?: Array<string>;
    filtersValues?: Array<string>;
    facetField?: string;
    exclusiveFacet?: boolean;
    facetRangeGap?: string;
    metaId?: number;
    metaType?: number;
    rangeMin?: string;
    rangeMax?: string;
    dateFacetGapType?: string;
    dateFacetGapRange?: string;
    rawQuery?: boolean;
    dateFormat?: string;
    faceted?: boolean;
    facetRange?: boolean;
}
