/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.1 - 7fdc88b413cfe49ca0d23a002cafdcc0ee5ee6ab
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentVersion } from './documentVersion';
import { Share } from './share';


export interface DataTransfer { 
    uid?: number;
    userName?: string;
    userSource?: string;
    lastActivityDate?: Date;
    version?: DocumentVersion;
    share?: Share;
    documentVersionUid?: number;
    isCompressed?: boolean;
    filePath?: string;
    dataSize?: number;
    hashMD5?: string;
    hashSHA?: string;
    transferMode?: number;
    hasBeenCheckedOutOnStart?: boolean;
    downloadToken?: string;
    password?: string;
    status?: DataTransfer.StatusEnum;
}
export namespace DataTransfer {
    export type StatusEnum = 'ACTIVE' | 'EXPIRED';
    export const StatusEnum = {
        ACTIVE: 'ACTIVE' as StatusEnum,
        EXPIRED: 'EXPIRED' as StatusEnum
    };
}
