/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.3-SNAPSHOT - 64dd5a468d54a39418677baf98332f99d5607d8d
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {DMEntityWrapper} from './dMEntityWrapper';


export interface DataMessage { 
    token?: string;
    sessionId?: string;
    dmEntityList?: Array<DMEntityWrapper>;
    parentUid?: number;
}
