/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.2-SNAPSHOT - 0e4caa5c6f07ea69fb28705b90f227cac1cd6682
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DMEntityAttribute { 
    indexed?: boolean;
    name?: string;
    value?: string;
}
