/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.2-SNAPSHOT - 0e4caa5c6f07ea69fb28705b90f227cac1cd6682
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DMEntity } from './dMEntity';
import { MetaValue } from './metaValue';


export interface Document extends DMEntity { 
    lastVersionId?: number;
    versionCreationDate?: Date;
    versionUpdateDate?: Date;
    folderUid?: number;
    mimeType?: string;
    extension?: string;
    checkedOut?: boolean;
    checkoutUser?: string;
    checkoutUserSource?: string;
    checkoutDate?: Date;
    length?: number;
    customVersion?: string;
    customVersionPending?: string;
    lastUpdateAuthor?: string;
    lastUpdateAuthorSource?: string;
    workflowStatusUid?: number;
    workflowStatusName?: string;
    validatorUserName?: string;
    validatorUserSource?: string;
    workflowName?: string;
    documentTypeName?: string;
    documentTypeUid?: number;
    indexScore?: number;
    outOfWorkflow?: boolean;
}
