/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.2-SNAPSHOT - 5f6a4372e643efa3abc97a7070cf07d4bb09747d
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocumentWorkflowStatusRequest { 
    userName?: string;
    userSource?: string;
    validatorUserName?: string;
    validatorUserSource?: string;
    documentUid?: number;
    workflowStatusUid?: number;
    date?: Date;
    status?: number;
    comment?: string;
    validationDate?: Date;
}
