/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.3-SNAPSHOT - 060527aa7377af83c5d622370343fc4fa7da64a7
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DMEntity } from './dMEntity';
import { MetaValue } from './metaValue';


export interface Document extends DMEntity { 
    lastVersionId?: number;
    versionCreationDate?: Date;
    versionUpdateDate?: Date;
    folderUid?: number;
    mimeType?: string;
    extension?: string;
    checkedOut?: boolean;
    checkoutUser?: string;
    checkoutUserSource?: string;
    checkoutDate?: Date;
    length?: number;
    customVersion?: string;
    customVersionPending?: string;
    lastUpdateAuthor?: string;
    lastUpdateAuthorSource?: string;
    workflowStatusUid?: number;
    workflowStatusName?: string;
    validatorUserName?: string;
    validatorUserSource?: string;
    workflowName?: string;
    documentTypeName?: string;
    documentTypeUid?: number;
    indexScore?: number;
    outOfWorkflow?: boolean;
}
