/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.1 - 7fdc88b413cfe49ca0d23a002cafdcc0ee5ee6ab
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Document } from './document';
import { DocumentType } from './documentType';


export interface DocumentVersion { 
    uid?: number;
    author?: string;
    authorSource?: string;
    creationDate?: Date;
    modificationDate?: Date;
    documentUid?: number;
    document?: Document;
    storagePath?: string;
    length?: number;
    documentType?: DocumentType;
    hashMD5?: string;
    hashSHA1?: string;
    customVersion?: string;
    customVersionPending?: string;
    lastUpdateAuthor?: string;
    lastUpdateAuthorSource?: string;
}
