/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.3-SNAPSHOT - 060527aa7377af83c5d622370343fc4fa7da64a7
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProcessWrapper { 
    id?: number;
    processId?: number;
    name?: string;
    description?: string;
    activationState?: string;
    configurationState?: string;
    deployedBy?: number;
    deploymentDate?: Date;
    displayName?: string;
    displayDescription?: string;
    iconPath?: string;
    lastUpdateDate?: Date;
    version?: string;
    url?: string;
}
