/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.3-SNAPSHOT - 060527aa7377af83c5d622370343fc4fa7da64a7
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SearchRequest } from './searchRequest';


export interface SearchRequestSecurity { 
    searchRequestId?: number;
    name?: string;
    source?: string;
    fullName?: string;
    type?: number;
    read?: boolean;
    write?: boolean;
    fullAccess?: boolean;
    searchRequest?: SearchRequest;
}
