/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.2-SNAPSHOT - 282608d038dbfdf7754fa4e049f180f36e0f635a
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Criteria } from './criteria';
import { SearchRequestSecurity } from './searchRequestSecurity';


export interface SearchRequest { 
    id?: number;
    name?: string;
    owner?: string;
    ownerSource?: string;
    criteriaList?: Array<Criteria>;
    criteriasListJson?: string;
    creationDate?: Date;
    updateDate?: Date;
    sortField?: string;
    sortDir?: string;
    virtualTree?: boolean;
    publicAccess?: boolean;
    published?: boolean;
    temporary?: boolean;
    searchSessionId?: string;
    securities?: Array<SearchRequestSecurity>;
    _transient?: boolean;
}
