/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.2-SNAPSHOT - 282608d038dbfdf7754fa4e049f180f36e0f635a
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DMEntity } from './dMEntity';
import { SearchRequest } from './searchRequest';


export interface SearchResponse { 
    results?: number;
    temporaryRequest?: SearchRequest;
    facetResponse?: boolean;
    rows?: Array<DMEntity>;
    documentIds?: Array<number>;
    virtualPath?: string;
    facetsData?: { [key: string]: any; };
    allfacetsData?: { [key: string]: any; };
}
