/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.2-SNAPSHOT - 5f6a4372e643efa3abc97a7070cf07d4bb09747d
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DMEntity } from './dMEntity';


export interface Share { 
    id?: number;
    creationDate?: Date;
    updateDate?: Date;
    creatorId?: string;
    creatorSource?: string;
    validatorId?: string;
    validatorSource?: string;
    targetUserId?: string;
    targetUserSource?: string;
    type?: Share.TypeEnum;
    notify?: boolean;
    read?: boolean;
    write?: boolean;
    fullAccess?: boolean;
    downloadToken?: string;
    downloadCount?: number;
    expirationDate?: Date;
    shareStatus?: Share.ShareStatusEnum;
    entity?: DMEntity;
}
export namespace Share {
    export type TypeEnum = 'SYSTEM' | 'EXTERNAL';
    export const TypeEnum = {
        SYSTEM: 'SYSTEM' as TypeEnum,
        EXTERNAL: 'EXTERNAL' as TypeEnum
    };
    export type ShareStatusEnum = 'ACTIVE' | 'EXPIRED' | 'DISABLED';
    export const ShareStatusEnum = {
        ACTIVE: 'ACTIVE' as ShareStatusEnum,
        EXPIRED: 'EXPIRED' as ShareStatusEnum,
        DISABLED: 'DISABLED' as ShareStatusEnum
    };
}
