/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.3-SNAPSHOT - 060527aa7377af83c5d622370343fc4fa7da64a7
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DMEntity } from './dMEntity';


export interface Share { 
    id?: number;
    creationDate?: Date;
    updateDate?: Date;
    creatorId?: string;
    creatorSource?: string;
    validatorId?: string;
    validatorSource?: string;
    targetUserId?: string;
    targetUserSource?: string;
    type?: Share.TypeEnum;
    notify?: boolean;
    read?: boolean;
    write?: boolean;
    fullAccess?: boolean;
    downloadToken?: string;
    downloadCount?: number;
    expirationDate?: Date;
    shareStatus?: Share.ShareStatus;
    entity?: DMEntity;
}
export namespace Share {
    export type TypeEnum = 'SYSTEM' | 'EXTERNAL';
    export const TypeEnum = {
        SYSTEM: 'SYSTEM' as TypeEnum,
        EXTERNAL: 'EXTERNAL' as TypeEnum
    };
    export type ShareStatus = 'ACTIVE' | 'EXPIRED' | 'DISABLED';
    export const ShareStatusEnum = {
        ACTIVE: 'ACTIVE' as ShareStatus,
        EXPIRED: 'EXPIRED' as ShareStatus,
        DISABLED: 'DISABLED' as ShareStatus
    };
}
