/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.2-SNAPSHOT - 73e8d1925ff0716b0a39dff428b76dec7209db16
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DMEntity } from './dMEntity';


export interface TaskInfo { 
    taskId?: string;
    messages?: string;
    owner?: string;
    startDate?: Date;
    status?: boolean;
    taskResultType?: TaskInfo.TaskResultTypeEnum;
    results?: { [key: string]: any; };
    targetEntity?: DMEntity;
}
export namespace TaskInfo {
    export type TaskResultTypeEnum = 'IMMEDIATE_RESULT' | 'FUTURE_RESULT';
    export const TaskResultTypeEnum = {
        IMMEDIATERESULT: 'IMMEDIATE_RESULT' as TaskResultTypeEnum,
        FUTURERESULT: 'FUTURE_RESULT' as TaskResultTypeEnum
    };
}
