/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.3-SNAPSHOT - 060527aa7377af83c5d622370343fc4fa7da64a7
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserWrapper { 
    id?: number;
    userName?: string;
    createdBy?: number;
    creationDate?: Date;
    firstName?: string;
    lastName?: string;
    title?: string;
    iconName?: string;
    iconPath?: string;
    jobTitle?: string;
    lastConnection?: Date;
    lastUpdate?: Date;
    managerUserId?: number;
}
