/**
 * Kimios API
 * Kimios Sample API
 *
 * OpenAPI spec version: 1.2.1 - 7fdc88b413cfe49ca0d23a002cafdcc0ee5ee6ab
 * Contact: documentation@kimios.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Group } from './group';


export interface User { 
    uid?: string;
    name?: string;
    firstName?: string;
    lastName?: string;
    phoneNumber?: string;
    avatar?: Array<string>;
    lastLogin?: Date;
    mail?: string;
    password?: string;
    authenticationSourceName?: string;
    groups?: Array<Group>;
    attributes?: { [key: string]: string; };
    enabled?: boolean;
    emails?: Array<string>;
    type?: number;
    id?: string;
}
